name       : pyparsing
version    : 2.3.1
release    : 5
source     :
    - https://github.com/pyparsing/pyparsing/archive/pyparsing_2.3.1.tar.gz : 6b4146fb3eb6c4f5798b9f1d67b9609efa106276ac875c534695e55a34409f07
license    : MIT
component  : programming.python
summary    : Python parsing module
description: |
    The pyparsing module is an alternative approach to creating and executing simple grammars, vs. the traditional lex/yacc approach, or the use of regular expressions. The pyparsing module provides a library of classes that client code uses to construct the grammar directly in Python code.
builddeps  :
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    %python_test unitTests.py
    %python3_test unitTests.py
