name       : pyparsing
version    : 2.0.6
release    : 3
source     :
    - https://pypi.python.org/packages/source/p/pyparsing/pyparsing-2.0.6.tar.gz : aea69042752ad7e9c436eea6ae5d40e73642e27f50edb6da4a2532030ef532da
license    : MIT
component  : programming.python
summary    : Python parsing module
description: |
    The pyparsing module is an alternative approach to creating and executing simple grammars, vs. the traditional lex/yacc approach, or the use of regular expressions. The pyparsing module provides a library of classes that client code uses to construct the grammar directly in Python code.
builddeps  :
    - pkgconfig(python-2.7)
    - pkgconfig(python3)
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
