name       : pyparsing
version    : 2.0.6
release    : 1
source     :
    - https://pypi.python.org/packages/source/p/pyparsing/pyparsing-2.0.6.tar.gz : aea69042752ad7e9c436eea6ae5d40e73642e27f50edb6da4a2532030ef532da
license    : MIT
summary    : Python parsing module
description: |
    The pyparsing module is an alternative approach to creating and executing 
    simple grammars, vs. the traditional lex/yacc approach, or the use of 
    regular expressions. The pyparsing module provides a library of classes 
    that client code uses to construct the grammar directly in Python code. 
builddeps  :
    - pkgconfig(python-2.7)
    - pkgconfig(python-3.4)
    - python-setuptools
    - python3-setuptools
build      : |
    for py in "python2" "python3.4"; do
        ${py} setup.py build
    done
install    : |
    for py in "python2" "python3.4"; do
        ${py} setup.py install --root=%installroot% --no-compile -O0
    done
